---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-rest-golang-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-rest-golang
  template:
    metadata:
      labels:
        app: simple-rest-golang
    spec:
      containers:
        - name: simple-rest-golang
          image: nginx:1.19-alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
          - name: volv
            mountPath: /usr/share/nginx/html
          ports:
          - containerPort: 80
          imagePullPolicy: Always
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: simple-rest-golang-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: tcp
  selector:
    app: simple-rest-golang
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-rest-golang-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: simple-rest-golang-service
          servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi
